apiVersion: apps/v1
kind: Deployment
metadata:
  name: petclinic-g
spec:
  selector:
    matchLabels:
      app: petclinic-g
  replicas: 6
  template:
    metadata:
      labels:
        app: petclinic-g
    spec:
      containers:
        - name: petclinic-g
          image: 953423807780.dkr.ecr.us-east-2.amazonaws.com/pc-ecr:99
          ports:
            - containerPort: 8080
          env:
            - name: MYSQL_URL
              valueFrom :
                configMapKeyRef :
                  name : configmap-petclinic
                  key : MYSQL_URL