apiVersion: v1
kind: Service
metadata:
  name: petclinic-g
spec:
  ports:
    - protocol: "TCP"
      port: 8080    # Port inside the cluster
      targetPort:   # Port exposed to the outside
  selector:
    app: petclinic-g
  type: LoadBalancer