apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-deployment
  labels:
    app: mysql
    tier: database
spec:
  selector: # mySQL Pod Should contain same labels
    matchLabels:
      app: mysql
  strategy:
    type: Recreate
  template:
    metadata:
      labels: # Must match 'Service' and 'Deployment' selectors
        app: mysql
        tier: database
    spec:
      containers:
        - name: mysqldb
          image: mysql:8.0
          imagePullPolicy: "IfNotPresent"
          env:
            - name: MYSQL_USER   # Setting Database host address from configMap
              valueFrom :
                configMapKeyRef :
                  name : configmap-petclinic
                  key : MYSQL_USER
            - name: MYSQL_DATABASE   # Setting Database host address from configMap
              valueFrom :
                configMapKeyRef :
                  name : configmap-petclinic
                  key : MYSQL_DATABASE
            - name: MYSQL_PASSWORD
              valueFrom :
                secretKeyRef :
                  name : secret-petclinic
                  key : MYSQL_PASSWORD
            - name: MYSQL_ROOT_PASSWORD
              valueFrom :
                secretKeyRef :
                  name : secret-petclinic
                  key : MYSQL_ROOT_PASSWORD
          ports:
            - containerPort: 3306
              name: mysql
          volumeMounts:
            - mountPath: /var/lib/mysql
              name: mysql-persistance-storage
      volumes:
        - name: mysql-persistance-storage
          persistentVolumeClaim:
            claimName: mysql-pv-claim-2