FROM python:3.8
WORKDIR /app
COPY ./requirements.txt /app/requirements.txt
RUN python -m venv venv
RUN . venv/bin/activate
# Install Python dependencies
RUN pip install --no-cache-dir -r requirements.txt

COPY . /app
CMD ["python", "main.py"]
