FROM python
RUN mkdir /app
ADD . /app
WORKDIR /app
RUN python -m venv venv
RUN . venv/bin/activate
# Install Python dependencies
RUN pip install --no-cache-dir -r requirements.txt
CMD ["python", "main.py"]
