apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: petclinic-application
  namespace: argocd
spec:
  project: default

  source:
    repoURL: https://gitlab.com/jmd-august/jmd-cd.git
    targetRevision: HEAD # Means always consider last commit in this repository
    path: k8s
  destination: 
    server: https://kubernetes.default.svc # we have argocd inside the same k8s cluster. If the cluster is external, we can mention that external address of that cluster
    namespace: default # If it is not default it can create a namespace, this will apply all the k8s manifest files in a new namespace. We can choose different namesapces with same configuration file.

  syncPolicy:
    syncOptions:
    - CreateNamespace=true # to create a namespace if its not available

    automated: # we want argocd to automatically sync any changes in git repo, default is turned off. keeping 'automated' attribute will enable it.
      selfHeal: true # Changes made to the live cluster will not trigger automated sync. With this, it will only consider changes from the manifest files only from the git repository
      prune: true # if we rename or delete any component or for example delete the whol svc object in the cluster, we want argocd to delete in the cluster as well

# by default argocd will sync the changes every 3 mnutes, if you dont want this delay, then we can configure a git webhook between the git repo and argocd
